#Based on template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-CMake.yml
name: Build

env:
  GH_TOKEN: ${{github.token}}
  Branch: ${{github.ref_name}}
  Artifacts: Release
  Title: ${{github.event.repository.name}}

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  Build:
    name: ${{matrix.Settings.Name}}-${{matrix.Configuration}}
    runs-on: windows-2022
    strategy:
      matrix:
        Configuration: [Release, Debug]
        Settings:
        - {
            Name: "Win32",
            Platform: "Win32",
            Architecture: "x86"
          }
        - {
            Name: "Win64",
            Platform: "x64",
            Architecture: "x64"
          }

    steps:

    - name: Clone repo and submodules
      run: git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git "${{github.workspace}}" --branch ${{env.Branch}} --recurse-submodules

    - name: Get current date, commit hash and count
      run: |
        echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
        echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
        echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV

    - name: Cache Vulkan SDK
      id: cache-vulkan-sdk
      uses: actions/cache@v5
      with:
        path: "C:\\VulkanSDK\\1.2.189.0"
        key: VulkanSDK-1.2.189.0
    - name: Install Vulkan SDK
      if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        echo "VULKAN_SDK=C:\VulkanSDK\1.2.189.0" >> $env:GITHUB_ENV
        Invoke-WebRequest -Method Get -Uri https://web.archive.org/web/20211204134012if_/https://sdk.lunarg.com/sdk/download/1.2.189.0/windows/VulkanSDK-1.2.189.0-Installer.exe -OutFile VulkanSDK.exe -UseBasicParsing
        Start-Process -Wait ./VulkanSDK.exe -ArgumentList "/S", "--accept-licenses", "--default-answer", "--confirm-command install", "com.lunarg.vulkan.32bit"
