#Based on template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-CMake.yml
name: Build

env:
  GH_TOKEN: ${{github.token}}
  Branch: ${{github.ref_name}}
  Platform: Win32, x64
  Configuration: Release, Debug
  Artifacts: build
  Title: ${{github.event.repository.name}}
  Executable: ${{github.event.repository.name}}.exe # *
#  DXSDK_DIR: C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\
#  VULKAN_VERSION: 1.1.130.0

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  ${{env.Platform}}-${{env.Configuration}}:
    strategy:
      matrix:
        Platform: ${{env.Platform}}
        Configuration: ${{env.Configuration}}

    runs-on: windows-2022
    steps:

    - name: Clone repo and submodules
      run: git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git "${{github.workspace}}" --branch ${{env.Branch}} --recurse-submodules #--depth 1 - Fetches entire commit history but breaks commit count

    - name: Get current date, commit hash and count
      run: |
        echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
        echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
        echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV

    - name: Configure
      run: cmake -A "${{matrix.Platform}}" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.Configuration}} #-DCMAKE_PREFIX_PATH=vcpkg\installed\x64-windows

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.Configuration}}

    - name: List files
      run: ls -R

    - name: Upload artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: "${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}"
        path: "${{github.workspace}}/${{env.Artifacts}}/"

    - name: Compress artifacts
      if: github.event_name == 'push'
      run: |
        mkdir ${{matrix.Configuration}}
        7z a "${{matrix.Configuration}}/${{env.Title}}.zip" "${{github.workspace}}/${{env.Artifacts}}/*" -mx=9
        cp "${{matrix.Configuration}}/${{env.Title}}.zip" "${{matrix.Configuration}}/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: Purge tag - latest-${{env.Branch}}
      if: github.event_name == 'push'
      run: |
        gh release delete latest-${{env.Branch}} --repo ${{github.repository}} --cleanup-tag --yes || true

    - name: ${{matrix.Configuration}} - archive-${{env.Branch}}
      if: github.event_name == 'push'
      run: |
        gh release create archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
        Build logs: https://github.com/${{github.repository}}/actions" || true
        gh release edit archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
        Build logs: https://github.com/${{github.repository}}/actions" || true
        gh release upload archive-${{env.Branch}} --repo ${{github.repository}} --clobber "${{matrix.Configuration}}/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: ${{matrix.Configuration}} - latest-${{env.Branch}}
      if: github.event_name == 'push'
      run: |
        gh release create latest-${{env.Branch}} --repo ${{github.repository}} --target ${{env.CommitHash}} --generate-notes --latest=true --title "${{env.Title}} r${{env.CommitCount}}@${{env.CommitHashShort}}" --notes "Build archive: https://github.com/${{github.repository}}/releases/tag/archive-${{env.Branch}}
        Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
        gh release upload latest-${{env.Branch}} --repo ${{github.repository}} --clobber "${{matrix.Configuration}}/${{env.Title}}.zip"
